const TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJzazA3MTFAc3JtaXN0LmVkdS5pbiIsImV4cCI6MTc3NzcwNzM2NCwiaWF0IjoxNzc3NzA2NDY0LCJpc3MiOiJBZmZvcmQgTWVkaWNhbCBUZWNobm9sb2dpZXMgUHJpdmF0ZSBMaW1pdGVkIiwianRpIjoiM2I4NDYwYmYtMTE5ZS00YjhiLTllNTQtMTM2ZTgzOTk5YmU4IiwibG9jYWxlIjoiZW4tSU4iLCJuYW1lIjoic3llZCB6b2hhaWIga2FyaW0iLCJzdWIiOiIyNDdmYjJjOC04OGQ3LTQ2MDgtYTQ1OC1kM2VkNzRmYWU0YzAifSwiZW1haWwiOiJzazA3MTFAc3JtaXN0LmVkdS5pbiIsIm5hbWUiOiJzeWVkIHpvaGFpYiBrYXJpbSIsInJvbGxObyI6InJhMjMxMTAwMzA1MDIzNSIsImFjY2Vzc0NvZGUiOiJRa2JweEgiLCJjbGllbnRJRCI6IjI0N2ZiMmM4LTg4ZDctNDYwOC1hNDU4LWQzZWQ3NGZhZTRjMCIsImNsaWVudFNlY3JldCI6IkNzZlpkS0trRHZtTmZVa2YifQ.irdp7nv9d0wBXL-fr5QUpiPiHD25EdJmufz1uuuQi3A";

export async function fetchNotifications() {
  const res = await fetch("/evaluation-service/notifications", {
    headers: {
      Authorization: `Bearer ${TOKEN}`
    }
  });

  return res.json();
}